name: Deploy

on:
  push:
    paths:
      - 'content.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install jinja2 pyyaml

      - name: Generate webpage from YAML
        run: |
          mkdir ./output
          python -c "
          import yaml
          from jinja2 import Template

          with open('content.yml') as f:
              data = yaml.safe_load(f)

          with open('template.html') as f:
              template = Template(f.read())

          with open('output/index.html', 'w') as f:
              f.write(template.render(**data))
          "

      - name: Check output directory
        run: ls -la ./output

      - name: Git status before add
        run: git status

      - name: Add files
        run: git add --force ./output/*

      - name: Git status after add
        run: git status

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output